import base64
import os


def read_file_return_base64ed_content(filename: str) -> str:
    with open(filename, "r", encoding="utf-8") as f:
        data = f.read()
    return base64.b64encode(data.encode("utf-8")).decode("utf-8")


def create_value_map(root: str) -> dict[str, str]:
    variable_file_content_map: dict[str, str] = {}
    for curr_root, _, files in os.walk(root):
        for file in files:
            file_path = os.path.join(curr_root, file)
            rel_path = os.path.relpath(file_path, root).replace(os.sep, "/")
            variable_file_content_map[rel_path] = read_file_return_base64ed_content(
                file_path
            )
    return variable_file_content_map


def main():
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    template_root = os.path.join(repo_root, "resources", "foam", "templates")
    output_ts = os.path.join(repo_root, "src", "features", "reports", "assets.ts")

    value_map = create_value_map(template_root)
    with open(output_ts, "w", encoding="utf-8") as output_file:
        def file_print(s: str):
            print(s, file=output_file)

        file_print("// This file is auto-generated by scripts/gen-report-assets.py")
        file_print("// Do not edit this file directly")
        file_print("// Run `python3 scripts/gen-report-assets.py` to regenerate this file")
        file_print("export let fs = {")
        for filename in sorted(value_map.keys()):
            file_print(f'\t"{filename.split(".")[0]}": atob("{value_map[filename]}"),')
        file_print("};")

    print(f"Generated {output_ts} successfully.")


if __name__ == "__main__":
    main()
